name = 'optica'
author = 'Dmitrii Tupitsyn'
cpp = 20
github = 'Old-est/optica'
license = ['MIT', 'https://github.com/Old-est/optica/blob/main/LICENSE']
navbar = ['namespaces', 'annotated']
# changelog = true

[warnings]
enabled = true
treat_as_errors = false
undocumented = true

[sources]
recursive_paths = [ '../include' ]
patterns        = [ '*.h', '*.hpp', '*.md' ]
strip_paths     = [ '../include' ]

