name: C++ Tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-15 cmake ninja-build

      - name: Set GCC 15 as default
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 100 \
                                   --slave /usr/bin/gcc gcc /usr/bin/gcc-15
          g++ --version  # проверить

      - name: Configure CMake
        run: cmake -DOPTICA_BUILD_TESTS=ON -S . -B build -G Ninja

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
